services:
  calculation_engine:
    build:
      context: ./calculation_engine
      dockerfile: Dockerfile
    image: myproject/calculation_engine:latest
    container_name: calculation_engine
    ports:
      - "8081:8081"

  server9:
    build:
      context: ./server9
      dockerfile: Dockerfile
    image: myproject/server9:latest
    container_name: server9
    depends_on:
      - calculation_engine
    environment:
      - MEGA_EMAIL=${MEGA_EMAIL}
      - MEGA_PWD=${MEGA_PWD}
      - MEGA_METRICS_FOLDER_PATH=${MEGA_METRICS_FOLDER_PATH}
    # If server9 needs to expose ports:
    # ports:
    #   - "9000:9000"
