version: '3.8'

services:
#  calculation_engine: # Commented out
#    build: # Commented out
#      context: ./calculation_engine # Commented out
#      dockerfile: Dockerfile # Commented out
#    container_name: calculation_engine_local # Commented out
#    ports: # Commented out
#      - "8081:8081" # Commented out
#    environment: # Commented out
#      - MEGA_EMAIL=${MEGA_EMAIL} # Commented out
#      - MEGA_PWD=${MEGA_PWD} # Commented out
#      - MEGA_METRICS_FOLDER_PATH=${MEGA_METRICS_FOLDER_PATH} # Commented out
    # Ensure GODEBUG and go run are handled by Dockerfile or command for calculation_engine if/when uncommented

  server9: # Ensure this is at the top level under services:
    build:
      context: ./server9
      dockerfile: Dockerfile
    container_name: server9_local # This is fine for local, Koyeb might override/ignore
    # depends_on: # You might want to comment this out if calculation_engine isn't running
    #   - calculation_engine
    environment:
      - MEGA_EMAIL=${MEGA_EMAIL}
      - MEGA_PWD=${MEGA_PWD}
      - MEGA_METRICS_FOLDER_PATH=${MEGA_METRICS_FOLDER_PATH}
    ports:
      - "9000:9000" # Koyeb will use this to expose the port
    # Add a command here if server9's Dockerfile doesn't have CMD/ENTRYPOINT
    # Example:
    # command: ["your-server9-start-command"]