[package]
name = "mega_exporter"
version = "0.1.0"
edition = "2024"

[dependencies]
mega = "0.6.0"  # Use the mega SDK
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"