name: keep-koyeb-awake

on:
  schedule:
    # every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  ping-koyeb:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Koyeb health endpoint
        run: |
          curl -fsS https://wiz-backend-giantwizard-0f2a46ea.koyeb.app/ || true
